"""Adding example response column

Revision ID: 1598313bc3fa
Revises: adf380e3bf6c
Create Date: 2026-01-02 17:44:34.835325

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1598313bc3fa"
down_revision: str | None = "adf380e3bf6c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("question_answers", schema=None) as batch_op:
        batch_op.add_column(sa.Column("response_example", sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("question_answers", schema=None) as batch_op:
        batch_op.drop_column("response_example")

    # ### end Alembic commands ###
