"""unique email

Revision ID: 9709ad836f30
Revises: 6adaa8e6a312
Create Date: 2025-12-19 17:55:23.963123

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9709ad836f30"
down_revision: Union[str, None] = "6adaa8e6a312"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.create_unique_constraint("uq_users_supabase_id", ["supabase_id"])
        batch_op.create_unique_constraint("uq_users_email", ["email"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_constraint("uq_users_email", type_="unique")
        batch_op.drop_constraint("uq_users_supabase_id", type_="unique")
    # ### end Alembic commands ###
