"""Decomposing global feedback

Revision ID: 71716a7b3994
Revises: b6f733d343a6
Create Date: 2025-12-16 14:01:56.641453

"""

import json
from collections.abc import Sequence
from datetime import datetime

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "71716a7b3994"
down_revision: str | None = "b6f733d343a6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "feedback",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("interview_id", sa.Integer(), nullable=False),
        sa.Column("overall_comment", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["interview_id"], ["interviews.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("interview_id"),
    )
    op.create_index(op.f("ix_feedback_id"), "feedback", ["id"], unique=False)
    op.create_table(
        "feedback_comments",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("feedback_id", sa.Integer(), nullable=False),
        sa.Column(
            "type",
            sa.Enum("STRENGTH", "WEAKNESS", "TIP", name="feedbackcommenttype"),
            nullable=False,
        ),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("order_index", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["feedback_id"], ["feedback.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_feedback_comments_feedback_id"),
        "feedback_comments",
        ["feedback_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_feedback_comments_id"), "feedback_comments", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_feedback_comments_type"), "feedback_comments", ["type"], unique=False
    )
    # ### end Alembic commands ###

    # Migrate existing data
    conn = op.get_bind()

    # Get all interviews with feedback
    result = conn.execute(
        sa.text(
            "SELECT id, global_feedback FROM interviews WHERE global_feedback IS NOT NULL AND global_feedback != ''"
        )
    )
    interviews = result.fetchall()

    print(f"Found {len(interviews)} interviews with feedback to migrate")

    migrated_count = 0
    error_count = 0

    for interview_id, global_feedback in interviews:
        try:
            # Parse the JSON feedback
            feedback_data = json.loads(global_feedback)

            # Skip if feedback is empty or invalid
            if not feedback_data or not isinstance(feedback_data, dict):
                print(f"Skipping interview {interview_id}: invalid feedback data")
                error_count += 1
                continue

            # Extract data with defaults
            overall_comment = feedback_data.get("overall_comment", "")
            strengths = feedback_data.get("strengths", [])
            weaknesses = feedback_data.get("weaknesses", [])
            tips = feedback_data.get("tips", [])
            now = datetime.utcnow()

            # Insert feedback record
            feedback_result = conn.execute(
                sa.text(
                    """
                INSERT INTO feedback (interview_id, overall_comment, created_at, updated_at)
                VALUES (:interview_id, :overall_comment, :created_at, :updated_at)
                RETURNING id
                """
                ),
                {
                    "interview_id": interview_id,
                    "overall_comment": overall_comment,
                    "created_at": now,
                    "updated_at": now,
                },
            )
            feedback_id = feedback_result.fetchone()[0]

            # Insert strength comments
            for idx, strength in enumerate(strengths):
                if strength:  # Skip empty strings
                    conn.execute(
                        sa.text(
                            """
                        INSERT INTO feedback_comments (feedback_id, type, content, order_index, created_at)
                        VALUES (:feedback_id, :type, :content, :order_index, :created_at)
                        """
                        ),
                        {
                            "feedback_id": feedback_id,
                            "type": "STRENGTH",
                            "content": strength,
                            "order_index": idx,
                            "created_at": now,
                        },
                    )

            # Insert weakness comments
            for idx, weakness in enumerate(weaknesses):
                if weakness:  # Skip empty strings
                    conn.execute(
                        sa.text(
                            """
                        INSERT INTO feedback_comments (feedback_id, type, content, order_index, created_at)
                        VALUES (:feedback_id, :type, :content, :order_index, :created_at)
                        """
                        ),
                        {
                            "feedback_id": feedback_id,
                            "type": "WEAKNESS",
                            "content": weakness,
                            "order_index": idx,
                            "created_at": now,
                        },
                    )

            # Insert tip comments
            for idx, tip in enumerate(tips):
                if tip:  # Skip empty strings
                    conn.execute(
                        sa.text(
                            """
                        INSERT INTO feedback_comments (feedback_id, type, content, order_index, created_at)
                        VALUES (:feedback_id, :type, :content, :order_index, :created_at)
                        """
                        ),
                        {
                            "feedback_id": feedback_id,
                            "type": "TIP",
                            "content": tip,
                            "order_index": idx,
                            "created_at": now,
                        },
                    )

            migrated_count += 1

        except (json.JSONDecodeError, KeyError, TypeError) as e:
            print(f"Error migrating feedback for interview {interview_id}: {e}")
            error_count += 1
            continue

    print(f"Successfully migrated {migrated_count} interview feedbacks")
    if error_count > 0:
        print(f"Failed to migrate {error_count} interviews")


def downgrade() -> None:
    # Migrate data back to JSON format
    conn = op.get_bind()

    # Get all feedbacks with their comments
    result = conn.execute(
        sa.text(
            """
        SELECT f.id, f.interview_id, f.overall_comment,
               fc.type, fc.content, fc.order_index
        FROM feedback f
        LEFT JOIN feedback_comments fc ON f.id = fc.feedback_id
        ORDER BY f.id, fc.type, fc.order_index
        """
        )
    )

    # Group by feedback_id
    feedbacks = {}
    for row in result:
        feedback_id = row[0]
        if feedback_id not in feedbacks:
            feedbacks[feedback_id] = {
                "interview_id": row[1],
                "overall_comment": row[2],
                "strengths": [],
                "weaknesses": [],
                "tips": [],
            }

        comment_type = row[3]
        content = row[4]

        if comment_type and content:
            if comment_type == "STRENGTH":
                feedbacks[feedback_id]["strengths"].append(content)
            elif comment_type == "WEAKNESS":
                feedbacks[feedback_id]["weaknesses"].append(content)
            elif comment_type == "TIP":
                feedbacks[feedback_id]["tips"].append(content)

    print(f"Migrating {len(feedbacks)} feedbacks back to JSON")

    # Update interviews with JSON feedback
    for feedback_data in feedbacks.values():
        feedback_json = {
            "score": 3,  # Default score
            "strengths": feedback_data["strengths"],
            "weaknesses": feedback_data["weaknesses"],
            "tips": feedback_data["tips"],
            "overall_comment": feedback_data["overall_comment"],
        }

        conn.execute(
            sa.text(
                "UPDATE interviews SET global_feedback = :feedback WHERE id = :interview_id"
            ),
            {
                "feedback": json.dumps(feedback_json, ensure_ascii=False),
                "interview_id": feedback_data["interview_id"],
            },
        )

    print("Successfully migrated data back to JSON format")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_feedback_comments_type"), table_name="feedback_comments")
    op.drop_index(op.f("ix_feedback_comments_id"), table_name="feedback_comments")
    op.drop_index(
        op.f("ix_feedback_comments_feedback_id"), table_name="feedback_comments"
    )
    op.drop_table("feedback_comments")
    op.drop_index(op.f("ix_feedback_id"), table_name="feedback")
    op.drop_table("feedback")
    # Drop enum type
    sa.Enum(name="feedbackcommenttype").drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
