"""Adding token usage table

Revision ID: cb4ac67be6f5
Revises: 99f3cb284271
Create Date: 2026-01-06 17:24:07.263436

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "cb4ac67be6f5"
down_revision: str | None = "99f3cb284271"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("token_usage", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("service", sa.String(), nullable=False, server_default="groq")
        )
        batch_op.add_column(sa.Column("character_count", sa.Integer(), nullable=True))
        batch_op.add_column(
            sa.Column("audio_duration_seconds", sa.Float(), nullable=True)
        )
        batch_op.alter_column(
            "prompt_tokens", existing_type=sa.INTEGER(), nullable=True
        )
        batch_op.alter_column(
            "completion_tokens", existing_type=sa.INTEGER(), nullable=True
        )
        batch_op.alter_column("total_tokens", existing_type=sa.INTEGER(), nullable=True)

    # Remove server_default after column is created (keeps schema clean)
    with op.batch_alter_table("token_usage", schema=None) as batch_op:
        batch_op.alter_column("service", server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("token_usage", schema=None) as batch_op:
        batch_op.alter_column(
            "total_tokens", existing_type=sa.INTEGER(), nullable=False
        )
        batch_op.alter_column(
            "completion_tokens", existing_type=sa.INTEGER(), nullable=False
        )
        batch_op.alter_column(
            "prompt_tokens", existing_type=sa.INTEGER(), nullable=False
        )
        batch_op.drop_column("audio_duration_seconds")
        batch_op.drop_column("character_count")
        batch_op.drop_column("service")
    # ### end Alembic commands ###
